services:
    blockchain_alice:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: blockchain_alice
        expose:
            - "3000" # nodeport, only needed between nodes
        ports:
            - "7080:8080" # apiport, accessed from your command line
        volumes:
            - ./blockchain_alice/:/app/simpleBlockchain/blockchain/
            - ./existingWallets/wallet_alice:/app/simpleBlockchain/wallet_alice
        command: ./cli server start -nodeport blockchain_alice:3000 -peernodeaddress blockchain_bob:3000 -walletname alice -ismining=true
    blockchain_bob:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: blockchain_bob
        expose:
            - "3000" # nodeport, only needed between nodes
        ports:
            - "7081:8080" # apiport, accessed from your command line
        volumes:
        - ./blockchain_bob/:/app/simpleBlockchain/blockchain/
        - ./existingWallets/wallet_bob:/app/simpleBlockchain/wallet_bob
        command: ./cli server start -nodeport blockchain_bob:3000 -peernodeaddress blockchain_alice:3000 -walletname bob


